---

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run playbook-all_nodes-add_Branch_Security_repo.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-add_Branch_Security_repo.yml

- name: 'Run playbook-all_nodes-install_vault.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_vault.yml

- name: 'Run playbook-vault_server-configure_and_start_vault.yml'
  ansible.builtin.import_playbook: playbook-vault_server-configure_and_start_vault.yml
