---
- name: 'Install, configure and start a PostgreSQL database'
  hosts: 'vault-client'
  gather_facts: true
  become: true

  pre_tasks:

    - name: 'Install ACL package to work around "temporary files" errors'
      ansible.builtin.package:
        name: 'acl'
        state: 'present'

  roles:

    - role: 'johanneskastl.install_and_start_postgresql'
