---
- name: 'Configure and start vault'
  hosts: 'all'
  gather_facts: true
  become: true

  tasks:

    - name: 'Manage vault user (add home directory)'
      ansible.builtin.user:
        name: 'vault'
        home: '/var/lib/vault/'
        create_home: true

    - name: 'Create /etc/vault.d/vault.hcl'
      ansible.builtin.template:
        src: 'vault.hcl.j2'
        dest: '/etc/vault.d/vault.hcl'
        owner: 'vault'
        group: 'vault'
        mode: '0644'
      notify:
        - 'Restart vault.service'

  handlers:

    - name: 'Restart vault.service'
      ansible.builtin.service:
        name: 'vault.service'
        state: 'restarted'
