---

#
# general configuration
#

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run playbook-all_nodes-add_Branch_Security_repo.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-add_Branch_Security_repo.yml

#
# Vault server
#

- name: 'Run playbook-server-install_vault-server.yml'
  ansible.builtin.import_playbook: playbook-server-install_vault-server.yml

- name: 'Run playbook-server-configure_and_start_vault_server.yml'
  ansible.builtin.import_playbook: playbook-server-configure_and_start_vault_server.yml

- name: 'Run playbook-server-add_entries_to_vault_server.yml'
  ansible.builtin.import_playbook: playbook-server-add_entries_to_vault_server.yml

- name: 'Run playbook-server-postgresql_vault_plugin.yml'
  ansible.builtin.import_playbook: playbook-server-postgresql_vault_plugin.yml

#
# Vault client VM
#

- name: 'Run playbook-client-install_vault-agent.yml'
  ansible.builtin.import_playbook: playbook-client-install_vault-agent.yml

- name: 'Run playbook-client-install_and_start_nginx.yml'
  ansible.builtin.import_playbook: playbook-client-install_and_start_nginx.yml

- name: 'Run playbook-client-postgresql_database.yml'
  ansible.builtin.import_playbook: playbook-client-postgresql_database.yml

- name: 'Run playbook-client-configure_and_start_vault_agent.yml'
  ansible.builtin.import_playbook: playbook-client-configure_and_start_vault_agent.yml
