---
- name: 'Add the Branch_Security zypper repository'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.add_zypper_repository'
      repository_name: 'home:ojkastl_buildservice:Branch_security'
      repository_baseurl: "https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/Branch_security/{{ ansible_distribution_version }}/"
      auto_import_keys: '1'
      when:
        - ansible_distribution == 'openSUSE Leap' or ansible_distribution == 'SLES'
