---
- name: 'Add entries to Vault server'
  hosts: 'vault'
  gather_facts: true
  become: false

  tasks:

    - name: 'Write a value'
      community.hashi_vault.vault_write:
        url: "http://{{ hostvars['vault']['ansible_default_ipv4']['address'] }}:8200"
        path: 'secret/data/foo'
        data:
          data:
            test: 'vagrant-libvirt'
        auth_method: 'token'
        token_file: 'vault_root_token'
        token_path: "{{ playbook_dir }}"
      delegate_to: 'localhost'
      become: false
