---
- name: 'Install nginx and start'
  hosts: 'vault-client'
  gather_facts: true
  become: true

  roles:

    - role: 'johanneskastl.install_one_or_more_packages'
      packages_to_be_installed:
        - 'nginx'

    - role: 'johanneskastl.start_and_or_enable_systemd_service'
      service_name: 'nginx'
      service_started: true
      service_enabled: true
