---
- name: 'Install, configure and start a PostgreSQL database'
  hosts: 'vault-client'
  gather_facts: true
  become: true

  pre_tasks:

    - name: 'Install ACL package to work around "temporary files" errors'
      ansible.builtin.package:
        name: 'acl'
        state: 'present'

  roles:

    - role: 'johanneskastl.install_and_start_postgresql'
      only_listen_on_localhost: false
      # The password should of course be encrypted in Ansible Vault,
      # not in cleartext in a playbook...
      postgresql_superuser_password: 'totallysecurepassword'
    - role: 'johanneskastl.configure_a_postgresql_database'
      # The passwords should of course be encrypted in Ansible Vault,
      # not in cleartext in a playbook...
      postgresql_login_user: 'postgres'
      postgresql_login_password: 'totallysecurepassword'
      postgresql_database_name: 'vault-example-database'
      postgresql_user_name: 'vault-user'
      postgresql_user_password: 'anothertotallysecurepassword'
      postgresql_user_role_attr_flags: 'SUPERUSER,CREATEROLE,CREATEDB'

  post_tasks:

    - name: 'Allow connections for all user from everywhere'
      community.postgresql.postgresql_pg_hba:
        dest: '/var/lib/pgsql/data/pg_hba.conf'
        contype: 'host'
        users: 'all'
        source: '0.0.0.0/0'
        databases: 'all'
        method: 'scram-sha-256'
      notify:
        - 'Restart postgresql'

  handlers:

    - name: 'Restart postgresql'
      ansible.builtin.service:
        name: 'postgresql.service'
        state: 'restarted'
