---
- name: 'Configure and start vault'
  hosts: 'vault'
  gather_facts: true
  become: true

  tasks:

    - name: 'Manage vault user (add home directory)'
      ansible.builtin.user:
        name: 'vault'
        home: '/var/lib/vault/'
        create_home: true

    - name: 'Create vault.service.d/'
      ansible.builtin.file:
        path: '/etc/systemd/system/vault.service.d/'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'
      notify:
        - 'Restart vault.service'

    - name: 'Create vault.service.d/override.conf'
      ansible.builtin.template:
        src: 'override.conf.j2'
        dest: '/etc/systemd/system/vault.service.d/override.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - 'Restart vault.service'

    - name: 'Create /etc/vault.d/vault.hcl'
      ansible.builtin.template:
        src: 'vault.hcl.j2'
        dest: '/etc/vault.d/vault.hcl'
        owner: 'vault'
        group: 'vault'
        mode: '0644'
      notify:
        - 'Restart vault.service'

    - name: 'Flush handlers'
      ansible.builtin.meta: flush_handlers

    - name: 'Fetch Vault root token'
      ansible.builtin.slurp:
        src: '/var/lib/vault/.vault-token'
      register: slurp_vault_token

    - name: 'Save root token on Ansible control node'
      ansible.builtin.copy:
        dest: 'group_vars/all/vault_root_token.yml'
        content: |
          ---
          vault_root_token: "{{ slurp_vault_token.content | b64decode }}"
      delegate_to: 'localhost'
      become: false

    - name: 'Print Vault root token'
      ansible.builtin.debug:
        msg: "The Vault root token is: {{ slurp_vault_token.content | b64decode }}"

  handlers:

    - name: 'Restart vault.service'
      ansible.builtin.service:
        name: 'vault.service'
        state: 'restarted'
        daemon_reload: true
