---
- name: 'Gather facts'
  hosts: 'all'
  gather_facts: true

- name: 'Configure and start vault agent'
  hosts: 'vault-client'
  gather_facts: true
  become: true

  pre_tasks:

    - name: 'Fetch Vault root token from local file'
      ansible.builtin.slurp:
        src: 'vault_root_token'
      register: slurp_vault_token
      delegate_to: 'localhost'
      become: false

    - name: 'Set fact for the Vault root token'
      ansible.builtin.set_fact:
        vault_root_token: "{{ slurp_vault_token.content | b64decode }}"

  tasks:

    - name: 'Add environment variable to /root/.bashrc'
      ansible.builtin.lineinfile:
        path: '/root/.bashrc'
        regexp: '^export VAULT_ADDR'
        line: "export VAULT_ADDR='http://{{ hostvars['vault']['ansible_default_ipv4']['address'] }}:8200'"
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Add environment variable to /home/vagrant/.bashrc'
      ansible.builtin.lineinfile:
        path: '/home/vagrant/.bashrc'
        regexp: '^export VAULT_ADDR'
        line: "export VAULT_ADDR='http://{{ hostvars['vault']['ansible_default_ipv4']['address'] }}:8200'"
        owner: 'vagrant'
        group: 'vagrant'
        mode: '0644'

    - name: 'Set permissions for vault user on directory/srv/www/htdocs/'
      ansible.builtin.file:
        path: '/srv/www/htdocs/'
        owner: 'vault'
        group: 'vault'
        mode: '0755'

    - name: 'Manage vault user (add home directory)'
      ansible.builtin.user:
        name: 'vault'
        home: '/var/lib/vault/'
        create_home: true

    - name: 'Create the .vault-token file'
      ansible.builtin.copy:
        dest: '/var/lib/vault/.vault-token'
        content: "{{ vault_root_token }}"
        owner: 'vault'
        group: 'vault'
        mode: '0600'
      notify:
        - 'Restart vault-agent.service'

    - name: 'Create the vault-agent.service file'
      ansible.builtin.template:
        src: 'vault-agent.service.j2'
        dest: '/etc/systemd/system/vault-agent.service'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - 'Restart vault-agent.service'

    - name: 'Create /etc/vault.d/vault-agent.hcl'
      ansible.builtin.template:
        src: 'vault-agent.hcl.j2'
        dest: '/etc/vault.d/vault-agent.hcl'
        owner: 'vault'
        group: 'vault'
        mode: '0644'
      notify:
        - 'Restart vault-agent.service'

    - name: 'Create /etc/vault.d/nginx.tmpl'
      ansible.builtin.template:
        src: 'nginx.tmpl.j2'
        dest: '/etc/vault.d/nginx.tmpl'
        owner: 'vault'
        group: 'vault'
        mode: '0644'
      notify:
        - 'Restart vault-agent.service'

    - name: 'Start vault-agent.service'
      ansible.builtin.service:
        name: 'vault-agent.service'
        state: 'started'
        enabled: false

    - name: 'Output URL'
      ansible.builtin.debug:
        msg: "The website containing the 'secret' from Vault is reachable at http://{{ ansible_default_ipv4['address'] }}"

  handlers:

    - name: 'Restart vault-agent.service'
      ansible.builtin.service:
        name: 'vault-agent.service'
        state: 'restarted'
